[project]
requires-python = ">= 3.8"
name="videoplayer"
version="0.1.0"
description="Smart Rewind Video Player for Accessibility Interventions"
dependencies=[
    "pyqt5",
    "pysrt",
    "qtawesome"
]

[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"